name: Deploy to Snowflake with Python

on:
  push:
    branches: [harness_deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies 
        run: pip install snowflake-connector-python snowflake-snowpark-python

      - name: Zip Python code for Snowflake
        run: |
          zip -r my_code.zip src/

      - name: Run deploy script
        env:
          PYTHONPATH: ${{ github.workspace }}
          SNOWFLAKE_ACCOUNT: ${{vars.SNOWFLAKE_ACCOUNT}}
          SNOWFLAKE_USERNAME: ${{secrets.SNOWFLAKE_USERNAME}}
          SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
          SNOWFLAKE_ROLE: ${{secrets.SNOWFLAKE_ROLE}}
          SNOWFLAKE_WAREHOUSE: ${{secrets.SNOWFLAKE_WAREHOUSE}}
          SNOWFLAKE_DATABASE: ${{secrets.SNOWFLAKE_DATABASE}}
          SNOWFLAKE_SCHEMA: ${{secrets.SNOWFLAKE_SCHEMA}}
        run: |
          python -m deploy_snowflake --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USERNAME --warehouse $SNOWFLAKE_WAREHOUSE --database $SNOWFLAKE_DATABASE --schema $SNOWFLAKE_SCHEMA --password $SNOWFLAKE_PASSWORD --role $SNOWFLAKE_ROLE

